Add MAX_FOUND_METRICS parameter to prevent from too large metrics
criteo-forks/graphite-web pull request #6
Opened 2017-05-02 15:28 UTC by Thib17

Enable limiting metric list retuned by the StandardFinder.
Do not limit as default.

2017-05-02 15:41 UTC, iksaif requested changes

2017-05-02 15:41 UTC, iksaif commented on webapp/graphite/finders/standard.py
> +      log.exception('Truncated metrics finding due to MAX_FOUND_METRICS limit (%d) reached for "%s"' % (settings.MAX_FOUND_METRICS, clean_pattern))
I think log.exception should be used only in an exception handler.

2017-05-02 15:41 UTC, iksaif commented on webapp/graphite/settings.py
> +MAX_FOUND_METRICS = 0
I propose:
```
# Fail if more than X metrics are returned
METRIC_FIND_FAILURE_THRESHOLD = 0
# Truncate if more than X metrics are returned
METRIC_FIND_TRUNCATE_THRESHOLD = 0
# Print a warning if more than X metrics are returned
METRICS_FIND_WARNING_THRESHOLD = 0
```

2017-05-02 15:41 UTC, iksaif commented on webapp/graphite/finders/standard.py
> +        if settings.MAX_FOUND_METRICS and found_leafs >= settings.MAX_FOUND_METRICS:
Set it to +inf, this way you the code will be easier to read.

2017-05-02 15:41 UTC, iksaif commented on webapp/graphite/settings.py
> +MAX_FOUND_METRICS = 0
Note: you may want to implement METRIC_FIND_FAILURE_THRESHOLD and METRICS_FIND_WARNING_THRESHOLD in the place that calls all the finders.

2017-05-03 15:26 UTC, Thib17 commented on webapp/graphite/finders/standard.py
> +        if settings.MAX_FOUND_METRICS and found_leafs >= settings.MAX_FOUND_METRICS:
Done

2017-05-03 15:26 UTC, Thib17 commented on webapp/graphite/finders/standard.py
> +      log.exception('Truncated metrics finding due to MAX_FOUND_METRICS limit (%d) reached for "%s"' % (settings.MAX_FOUND_METRICS, clean_pattern))
Done

2017-05-03 15:26 UTC, Thib17 commented on webapp/graphite/settings.py
> +MAX_FOUND_METRICS = 0
Done

2017-05-04 07:11 UTC, iksaif requested changes

2017-05-04 07:11 UTC, iksaif commented on webapp/graphite/storage.py
> +    if matched_leafs >= settings.METRICS_FIND_WARNING_THRESHOLD:
I find it easier to read when intermediate variables are used
```
warn_threshold =  settings.METRICS_FIND_WARNING_THRESHOLD
if matched_leafs > warn_treshold:
 log.rendering(..., warn_threhsold)
```

2017-05-04 07:11 UTC, iksaif commented on webapp/graphite/settings.py
> +METRICS_FIND_WARNING_THRESHOLD = float('Inf') # Print a warning if more than X metrics are returned
You may want to explain more why we need these settings.

2017-05-04 07:11 UTC, iksaif commented on webapp/graphite/finders/standard.py
> +    found_leafs, truncated_leafs = 0, 0
I think could you put both thresholds in intermediary variables, that would make the code easier to read:
truncate_threshold = setings.BLABLA..

2017-05-04 07:11 UTC, iksaif commented on webapp/graphite/finders/standard.py
> +            if found_leafs >= settings.METRICS_FIND_WHISPER_TRUNCATE_THRESHOLD:
you can yield later to factorize the code:

node = None
if whsiper:
  node = LeafNode(...)
elif gzip:
  node = LeafNode(...)

if node is not None:
   threshold checks
   yield node

2017-05-04 07:11 UTC, iksaif commented on webapp/graphite/finders/standard.py
> +    elif truncated_leafs > 0:
don't you want to exit the loop here ?

2017-05-04 15:52 UTC, Thib17 commented on webapp/graphite/storage.py
> +    if matched_leafs >= settings.METRICS_FIND_WARNING_THRESHOLD:
Done

2017-05-04 15:52 UTC, Thib17 commented on webapp/graphite/settings.py
> +METRICS_FIND_WARNING_THRESHOLD = float('Inf') # Print a warning if more than X metrics are returned
Done

2017-05-04 15:53 UTC, Thib17 commented on webapp/graphite/finders/standard.py
> +    found_leafs, truncated_leafs = 0, 0
As discussed, refocussed on global threshold for now. Will work later on whisper finder

2017-05-04 15:53 UTC, Thib17 commented on webapp/graphite/finders/standard.py
> +            if found_leafs >= settings.METRICS_FIND_WHISPER_TRUNCATE_THRESHOLD:
As discussed, refocussed on global threshold for now. Will work later on whisper finder

2017-05-04 15:53 UTC, Thib17 commented on webapp/graphite/finders/standard.py
> +    elif truncated_leafs > 0:
As discussed, refocussed on global threshold for now. Will work later on whisper finder

2017-05-05 07:06 UTC, iksaif commented on setup.py
> +      version='1.1.0-criteo1',
can you rebase and remove this commit ? :)

2017-05-05 07:08 UTC, iksaif commented on webapp/graphite/storage.py
> +      log.rendering("warning : Large metrics find reaching METRICS_FIND_WARNING_THRESHOLD (%d > %d) for '%s'" %
"Query %s on %s yields more than %d results (warning threshold is %d)"

2017-05-05 07:08 UTC, iksaif commented on webapp/graphite/storage.py
> +        raise Exception("Failed metrics find due to METRICS_FIND_FAILURE_THRESHOLD reached (%d) for '%s'" % (fail_threshold, clean_pattern))
"Query %s on %s yields more than %d results (failure threshold is %d)"

2017-05-05 09:13 UTC, Thib17 commented on setup.py
> +      version='1.1.0-criteo1',
Done

2017-05-05 09:13 UTC, Thib17 commented on webapp/graphite/storage.py
> +      log.rendering("warning : Large metrics find reaching METRICS_FIND_WARNING_THRESHOLD (%d > %d) for '%s'" %
Done

2017-05-05 09:13 UTC, Thib17 commented on webapp/graphite/storage.py
> +        raise Exception("Failed metrics find due to METRICS_FIND_FAILURE_THRESHOLD reached (%d) for '%s'" % (fail_threshold, clean_pattern))
Done

2017-05-05 09:23 UTC, iksaif approved these changes

2017-05-05 09:23 UTC, merged